import { LegalPage, LegalSection, LegalList } from '../components/layout/LegalPage'
import { SITE } from '../lib/site'

const TOC = [
  { id: 'overview', label: '1. Overview' },
  { id: 'who', label: '2. Who we are' },
  { id: 'collect', label: '3. Data we collect' },
  { id: 'how', label: '4. How we use data' },
  { id: 'basis', label: '5. Legal basis' },
  { id: 'minors', label: '6. Minors & parental consent' },
  { id: 'share', label: '7. Sharing & sub-processors' },
  { id: 'retain', label: '8. Retention' },
  { id: 'residency', label: '9. Data residency' },
  { id: 'rights', label: '10. Your rights' },
  { id: 'security', label: '11. Security' },
  { id: 'cookies', label: '12. Cookies' },
  { id: 'changes', label: '13. Changes' },
  { id: 'contact', label: '14. Contact the DPO' },
]

export default function Privacy() {
  return (
    <LegalPage
      eyebrow="Legal"
      title="Privacy Policy"
      intro="How QYNE collects, uses, and protects personal data — written to be readable, and aligned with India's Digital Personal Data Protection Act, 2023."
      path="/privacy"
      meta={{ effective: '01 June 2026', version: '1.0' }}
      toc={TOC}
    >
      <p className="text-[14px] leading-relaxed text-faint">
        <strong>Placeholder text.</strong> The contents on this page are dummy
        compliance copy provided for layout and review. Final privacy
        disclosures will be published before general availability.
      </p>

      <LegalSection id="overview" title="1. Overview">
        <p>
          This Privacy Policy explains what personal data QYNE collects when
          academies and athletes use our platform, how we use it, who we share
          it with, and the rights you have over it.
        </p>
        <p>
          We collect only what we need to operate the Service. We do not sell
          personal data. We do not run advertising. Plans are generated by
          rules-engine logic, not by selling attention.
        </p>
      </LegalSection>

      <LegalSection id="who" title="2. Who we are">
        <p>
          {SITE.legalName} (<strong>“QYNE”</strong>) is the Data Fiduciary for
          personal data processed through the Service, except where an academy
          configures QYNE as its processor, in which case the academy is the
          Fiduciary and QYNE is the Data Processor.
        </p>
      </LegalSection>

      <LegalSection id="collect" title="3. Data we collect">
        <p>We collect the following categories of data:</p>
        <LegalList
          items={[
            <span key="a">
              <strong>Account data</strong> — name, email, role, academy
              affiliation, password hash.
            </span>,
            <span key="b">
              <strong>Athlete profile</strong> — sport, position, date of
              birth, height, weight, training history, parent/guardian contact
              for minors.
            </span>,
            <span key="c">
              <strong>Wearable data</strong> — heart-rate variability, sleep,
              resting heart rate, training load, steps, and similar signals
              from Garmin, Apple Health, WHOOP, Health Connect, and other
              integrations you connect.
            </span>,
            <span key="d">
              <strong>Self-reported data</strong> — morning check-ins,
              perceived exertion, soreness, mood, sleep quality.
            </span>,
            <span key="e">
              <strong>Coach activity</strong> — plan approvals, edits,
              comments, and the audit trail of who approved which plan when.
            </span>,
            <span key="f">
              <strong>Device &amp; usage data</strong> — IP address, device
              type, browser, app version, logs, and product analytics events.
            </span>,
          ]}
        />
      </LegalSection>

      <LegalSection id="how" title="4. How we use data">
        <LegalList
          items={[
            'Generate readiness scores and draft training plans for review by coaches.',
            'Produce monthly parent reports for under-18 athletes.',
            'Operate, secure, and improve the Service.',
            'Respond to support requests and communicate service updates.',
            'Comply with legal obligations and enforce our Terms.',
            'Produce de-identified, aggregated insights — never tied to an individual — to improve our models.',
          ]}
        />
      </LegalSection>

      <LegalSection id="basis" title="5. Legal basis">
        <p>
          Under the DPDP Act, we process personal data on the basis of consent
          (collected during onboarding) and on the legitimate uses permitted by
          the Act, such as performance of contract and compliance with law.
        </p>
      </LegalSection>

      <LegalSection id="minors" title="6. Minors & parental consent">
        <p>
          We treat all athletes under 18 as minors. Onboarding a minor requires
          verifiable consent from a parent or legal guardian, captured through
          a documented workflow. Parents can review, request correction, or
          request deletion of their child's data at any time by contacting our
          Data Protection Officer.
        </p>
        <p>
          We do not use minors' personal data for tracking, behavioural
          monitoring, or targeted advertising. Ever.
        </p>
      </LegalSection>

      <LegalSection id="share" title="7. Sharing & sub-processors">
        <p>
          We share data with a small number of vetted service providers who
          act on our behalf and only on documented instructions:
        </p>
        <LegalList
          items={[
            <span key="a">
              <strong>Cloud hosting</strong> — managed Indian regions of a Tier-1
              cloud provider.
            </span>,
            <span key="b">
              <strong>Email delivery</strong> — for transactional emails such as
              consent confirmations and parent reports.
            </span>,
            <span key="c">
              <strong>Error monitoring</strong> — to detect and resolve bugs;
              configured to scrub personal identifiers.
            </span>,
            <span key="d">
              <strong>Wearable platforms</strong> — only when you explicitly
              connect them, and only for the scopes you authorise.
            </span>,
          ]}
        />
        <p>
          We publish a current list of sub-processors and notify customers of
          material changes in advance.
        </p>
      </LegalSection>

      <LegalSection id="retain" title="8. Retention">
        <p>
          We retain personal data only as long as needed to operate the
          Service or as required by law. Indicative defaults:
        </p>
        <LegalList
          items={[
            'Account and athlete profile — for the duration of the subscription plus 90 days.',
            'Wearable and check-in data — for the duration of the subscription plus 180 days, to support training-load analysis.',
            'Coach audit trail — for 7 years, to support compliance and incident review.',
            'Server logs — for 90 days.',
          ]}
        />
        <p>
          Customers can request earlier deletion or longer retention through a
          documented agreement.
        </p>
      </LegalSection>

      <LegalSection id="residency" title="9. Data residency">
        <p>
          Primary storage of personal data is in cloud regions located within
          India. We do not transfer personal data outside India except where
          explicitly permitted by law and disclosed in advance.
        </p>
      </LegalSection>

      <LegalSection id="rights" title="10. Your rights">
        <p>As a Data Principal under the DPDP Act, you have the right to:</p>
        <LegalList
          items={[
            'Access the personal data we hold about you.',
            'Request correction of inaccurate or incomplete data.',
            'Request erasure where the data is no longer necessary.',
            'Withdraw consent at any time.',
            'Nominate another person to exercise these rights on your behalf.',
            'File a complaint with the Data Protection Board of India.',
          ]}
        />
        <p>
          To exercise any of these rights, contact our Data Protection Officer
          at <a href={`mailto:${SITE.email}`}>{SITE.email}</a>. We will
          respond within the statutory timeline.
        </p>
      </LegalSection>

      <LegalSection id="security" title="11. Security">
        <p>
          We protect personal data with encryption in transit and at rest,
          least-privilege access controls, audit logging, and routine security
          reviews. See our <a href="/security">Security page</a> for the full
          control framework.
        </p>
      </LegalSection>

      <LegalSection id="cookies" title="12. Cookies">
        <p>
          We use a minimal set of cookies and similar technologies — strictly
          necessary cookies for authentication and session management, and
          first-party analytics that respect Do Not Track. We do not embed
          third-party advertising trackers.
        </p>
      </LegalSection>

      <LegalSection id="changes" title="13. Changes">
        <p>
          We may update this Privacy Policy from time to time. Material changes
          will be communicated by email or through the Service at least 30
          days before they take effect.
        </p>
      </LegalSection>

      <LegalSection id="contact" title="14. Contact the DPO">
        <p>
          Our Data Protection Officer can be reached at{' '}
          <a href={`mailto:${SITE.email}`}>{SITE.email}</a>. Postal
          address: {SITE.legalName}, Bangalore, India.
        </p>
      </LegalSection>
    </LegalPage>
  )
}
